name: Push on Docker

on:
    push:
        branches: [main]

jobs:
    docker:
        name: Build and release to Docker
        runs-on: ubuntu-latest
        steps:
            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: deuchnord/f2ap:unstable
