name: Code quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    black:
        name: Check code style
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - uses: psf/black@20.8b1

    pycln:
        name: Check imports
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - run: |
                  pip install poetry
                  poetry install
            - run: |
                  poetry run pycln --check f2ap tests
